// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKuYnHU2uVZ6DRLDuQ3WE1L0uZF2h2nu8',
    appId: '1:44126273424:android:cc2d00612460b43622bd15',
    messagingSenderId: '44126273424',
    projectId: 'ms-live-app-3fe90',
    databaseURL: 'https://ms-live-app-3fe90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ms-live-app-3fe90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHg6yNrmh8dAnDeyJX6LLGRVxJU8zSjxA',
    appId: '1:44126273424:ios:1af8a1499391a42022bd15',
    messagingSenderId: '44126273424',
    projectId: 'ms-live-app-3fe90',
    databaseURL: 'https://ms-live-app-3fe90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ms-live-app-3fe90.firebasestorage.app',
    iosClientId: '44126273424-n7ok6qj02le05kfk1hnlja17ps2lahn3.apps.googleusercontent.com',
    iosBundleId: 'com.cutelive.app.cuteLive',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjzYmtm7PBROoujphppwcr00wfXAdaxE',
    appId: '1:44126273424:web:a0304404b842ef9822bd15',
    messagingSenderId: '44126273424',
    projectId: 'ms-live-app-3fe90',
    authDomain: 'ms-live-app-3fe90.firebaseapp.com',
    databaseURL: 'https://ms-live-app-3fe90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ms-live-app-3fe90.firebasestorage.app',
  );

}