// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBuo5qrFOjutxhgSd4vl05iXkDpO58jlU',
    appId: '1:645699802815:android:527136b860cfab1ab7580a',
    messagingSenderId: '645699802815',
    projectId: 'cute-live-app',
    databaseURL: 'https://cute-live-app-default-rtdb.firebaseio.com',
    storageBucket: 'cute-live-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd_CgY12lToRCHNhob9MNLV1Vfv_uNT-w',
    appId: '1:645699802815:ios:6626c06fee76fe86b7580a',
    messagingSenderId: '645699802815',
    projectId: 'cute-live-app',
    databaseURL: 'https://cute-live-app-default-rtdb.firebaseio.com',
    storageBucket: 'cute-live-app.firebasestorage.app',
    androidClientId: '645699802815-h0nltv1fakn5vjmppv6ts2r1q1n22l5p.apps.googleusercontent.com',
    iosClientId: '645699802815-1jggcnid488b836op4g2g4alicoa5te5.apps.googleusercontent.com',
    iosBundleId: 'com.cutelive.app.cuteLive',
  );

}